---
title: "Figures"
output: 
  word_document:
    reference_docx: carey_template.docx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(AreaGrowthRex)
library(ggplot2)
library(here)
library(ggpubr)
library(devtools)
library(r4ss)
library(patchwork)
```

```{r plotting themes, include=FALSE}

# Presentation theme
.THEME <- theme(panel.grid.major.x = element_blank(), panel.grid.minor.y = element_blank(), panel.grid.major.y = element_blank() )
.THEME <- .THEME + theme(text=element_text(size=18)) + theme(axis.title.x=element_text(size=24) ,axis.title.y=element_text(size=24, angle = 90,vjust = +2)) +
theme(legend.position = "bottom")
theme_set(.THEME)
#.THEME <- .THEME + theme( panel.background = element_rect(fill="white"), #panel.border = element_rect(colour="black", fill=NA, size=1))

# Manuscript theme
.THEME <- theme(panel.grid.major.x = element_blank(), panel.grid.minor.y = element_blank(), panel.grid.major.y = element_blank() )
.THEME <- .THEME + theme(text=element_text(size=12)) + theme(axis.title.x=element_text(size=12) ,axis.title.y=element_text(size=12, angle = 90,vjust = +2)) +
theme(legend.position = "bottom")
theme_set(.THEME)
```

```{r readfiles, include = FALSE, message = FALSE, warning = FALSE}
run_dir<-"C:/Users/carey.mcgilliard/Work/FlatfishAssessments/2025/rex_cie_review/runs"

M1 <- file.path(run_dir, "run7_2021_new_data_and_sampler")
M2 <- file.path(run_dir, "run9_as_for_7_early_age_mat")
M3 <- file.path(run_dir, "run10_as_for_7_late_age_mat")
M4 <- file.path(run_dir, "run11_as_for_7_est_male_m")

M5 <- file.path(run_dir,"run1_2021_accepted")
M6 <- file.path(run_dir,"run8_2021_sampler_no_new_data")
M7 <- file.path(run_dir,"run13_2021_correct_survey_biomass_and_fishery_sampler")
M8 <- file.path(run_dir,"run7_2021_new_data_and_sampler")

Mlab.1 <- "new_data"
Mlab.2 <- "early_maturity"
Mlab.3 <- "late_maturity"
Mlab.4 <- "estimate_male_M"

Mlab.5 <- "2021 model"
Mlab.6 <- "sampler"
Mlab.7 <- "sampler and survbio edits"
Mlab.8 <- "sampler survbio edits and new data"

Mlabels <- c(Mlab.1, Mlab.2, Mlab.3, Mlab.4)
Mlabels2 <-c(Mlab.5, Mlab.6, Mlab.7, Mlab.8)

MasterList <- r4ss::SSgetoutput(dirvec = c(M1, M2, M3, M4), getcomp = TRUE, getcovar = TRUE)

MasterList2<-r4ss::SSgetoutput(dirvec = c(M5, M6, M7, M8),getcomp = TRUE, getcovar = TRUE)
#SummaryList<-r4ss::SSsummarize(MasterList)
```


```{r plot estimated pop dynamics, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Figure 6. Observed catches and estimated spawning biomass, recruitment, and fishing intensity (1-spawning potential ratio) for each of the four alternative models with new data added"}
#need to make y-axis on ssb go to zero
ssbplot<-plot_ssbs(ssruns=MasterList,mlabel=Mlabels,showxlabel =   FALSE,showlegend = "none")
recplot<-plot_recs(ssruns = MasterList,mlabel = Mlabels,showxlabel = FALSE,showlegend = "none")

#CHECK DEFINITION OF SPRratio_ in DERIVED QUANTITIES! I think it's 1-SPR. Does r4ss skip plotting the last year? Should I?
fi_plot<-plot_one_minus_spr(ssruns = MasterList,mlabel = Mlabels,showxlabel = FALSE,showlegend = "yes")

#stuff<-get_catch_data(ssruns = MasterList,mlabel = Mlabels)
total_catch_plot<-plot_total_catch(ssruns = MasterList,mlabel = Mlabels,showxlabel = TRUE,showlegend = "none")

bigfig<-(total_catch_plot/ssbplot/recplot/fi_plot)

ggsave(filename = file.path(run_dir,"cie_comparisons",paste0("Compare_TimeSeries.png")),device = "png",width = 8.5,height = 11)
```

```{r plot estimated pop dynamics, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Figure 6. Observed catches and estimated spawning biomass, recruitment, and fishing intensity (1-spawning potential ratio) for the 2021 accepted model, the model using Sampler for fishery age composition calculations, and the model using Sampler with all new data added"}
#need to make y-axis on ssb go to zero
ssbplot<-plot_ssbs(ssruns=MasterList2,mlabel=Mlabels2,showxlabel =   FALSE,showlegend = "none")
recplot<-plot_recs(ssruns = MasterList2,mlabel = Mlabels2,showxlabel = FALSE,showlegend = "none")

#CHECK DEFINITION OF SPRratio_ in DERIVED QUANTITIES! I think it's 1-SPR. Does r4ss skip plotting the last year? Should I?
fi_plot<-plot_one_minus_spr(ssruns = MasterList2,mlabel = Mlabels2,showxlabel = FALSE,showlegend = "yes")

#stuff<-get_catch_data(ssruns = MasterList,mlabel = Mlabels)
total_catch_plot<-plot_total_catch(ssruns = MasterList2,mlabel = Mlabels2,showxlabel = TRUE,showlegend = "none")

bigfig<-(total_catch_plot/ssbplot/recplot/fi_plot)

ggsave(filename = file.path(run_dir,"cie_comparisons",paste0("Compare_TimeSeries_old_new_data.png")),device = "png",width = 8.5,height = 11)
```

```{r plot growth, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Figure 3. Raw bottom trawl survey data length-at-age by area and sex, overlayed with mean length-at-age for each model (columns) and 90% asymptotic uncertainty intervals around the means (shaded areas). The Eastern GOA is shown in green and the Western-Central GOA is shown in blue."}
g<-plot_growth(ssruns=MasterList,sslabels=Mlabels,savePlot = FALSE)
g
ggsave(filename = file.path(run_dir,"cie_comparisons",paste0("Plot_Growth_AllModels.png")),device = "png",width = 10,height = 5)

```

```{r plot growth, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Figure 3. Raw bottom trawl survey data length-at-age by area and sex, overlayed with mean length-at-age for each model (columns) and 90% asymptotic uncertainty intervals around the means (shaded areas). The Eastern GOA is shown in green and the Western-Central GOA is shown in blue."}
g<-plot_growth(ssruns=MasterList2,sslabels=Mlabels2,savePlot = FALSE)
g
ggsave(filename = file.path(run_dir,"cie_comparisons",paste0("Plot_Growth_old_new_models.png")),device = "png",width = 10,height = 5)

```


```{r plot selectivity overlaid on maturity, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Figure 7. Fishery and survey selectivity-at-age across models for males and females. Plots for females are overlaid on maturity-at-age"}
p<-plot_selex_maturity(ssruns=MasterList,mlabels=Mlabels) 
ggsave(filename = file.path(run_dir,"cie_comparisons",paste0("Plot_Selex_Maturity_AllModels.png")),device = "png",width = 10,height = 7)


```

```{r plot selectivity overlaid on maturity, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Figure 7. Fishery and survey selectivity-at-age across models for males and females. Plots for females are overlaid on maturity-at-age"}
p<-plot_selex_maturity(ssruns=MasterList2,mlabels=Mlabels2)
ggsave(filename = file.path(run_dir,"cie_comparisons",paste0("Plot_Selex_Maturity_old_new_data.png")),device = "png",width = 10,height = 7)


```

```{r plot length comps two area models, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Figure 4. Fits (lines) to female and male fishery length composition with data aggregated by year (shaded regions) for the two-area area model."}
q<-plot_comps_twoarea(ssruns = MasterList2, narea = 2, mnames = Mlabels2,comptype = "length")
q$combo
ggsave(filename = file.path(run_dir,"cie_comparisons",paste0("Agg_fits_length_comps_old_new.png")),device = "png",width = 10,height = 7)
```

```{r plot length comps two area models, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Figure 4. Fits (lines) to female and male fishery length composition with data aggregated by year (shaded regions) for the two-area area model."}
q<-plot_comps_twoarea(ssruns = MasterList, narea = 2, mnames = Mlabels,comptype = "length")
q$combo
ggsave(filename = file.path(run_dir,"cie_comparisons",paste0("Agg_fits_length_comps_all_models.png")),device = "png",width = 10,height = 7)
```


```{r plot ages two area models, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Figure 5. Fits (lines) to female and male fishery age composition with data aggregated by year (shaded regions) for the two-area area model with fishery ages included in model inputs."}
#age plots not working.
q<-plot_comps_twoarea(ssruns = MasterList2, narea = 2, mnames = Mlabels2,comptype = "age")
q$combo

ggsave(filename = file.path(run_dir,"cie_comparisons",paste0("Agg_fits_age_comps_old_new.png")),device = "png",width = 10,height = 7)
```
```{r plot ages two area models, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Figure 5. Fits (lines) to female and male fishery age composition with data aggregated by year (shaded regions) for the two-area area model with fishery ages included in model inputs."}
#age plots not working.
q<-plot_comps_twoarea(ssruns = MasterList, narea = 2, mnames = Mlabels,comptype = "age")
q$combo

ggsave(filename = file.path(run_dir,"cie_comparisons",paste0("Agg_fits_age_comps_all_models.png")),device = "png",width = 10,height = 7)
```
```{r plot ages two area models, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Figure 5. Fits (lines) to female and male fishery age composition with data aggregated by year (shaded regions) for the two-area area model with fishery ages included in model inputs."}

p<-compare_index_fits(ssruns = MasterList,mlabels=Mlabels)
ggsave(filename = file.path(run_dir,"cie_comparisons","index_fits_all_models.png"),device = "png",width = 10, height = 7)

pp<-compare_index_fits(ssruns = MasterList2,mlabels = Mlabels2)
ggsave(filename = file.path(run_dir,"cie_comparisons","index_fits_old_new.png"),device = "png",width = 10, height = 7)
```
```{r get the projection data file for each model run but right now organizing the projections manually within the projections folder, echo = FALSE, message = FALSE, warning = FALSE}

#get parameter tables:
old_new_params<-compare_bio_pars(MasterList2,Mlabels2)
write.csv(old_new_params,file.path(run_dir,"cie_comparisons","old_new_time_inv_params.csv"))

all_params<-compare_bio_pars(MasterList,Mlabels)
write.csv(all_params,file.path(run_dir,"cie_comparisons","all_time_inv_params.csv"))

get_projections(mydir = here(M1) ,MyOutput = MasterList[[1]],NagesProject = 20,FirstYr = 1982,LastYr = 2021,RecruitmentAge=3,species="Rex")

get_projections(mydir = here(M2) ,MyOutput = MasterList[[2]],NagesProject = 20,FirstYr = 1982,LastYr = 2021,RecruitmentAge=3,species="Rex")

get_projections(mydir = here(M3) ,MyOutput = MasterList[[3]],NagesProject = 20,FirstYr = 1982,LastYr = 2021,RecruitmentAge=3,species="Rex")

get_projections(mydir = here(M4) ,MyOutput = MasterList[[4]],NagesProject = 20,FirstYr = 1982,LastYr = 2021,RecruitmentAge=3,species="Rex")

```

```{r grab ref pts from projection results, echo = FALSE, message = FALSE, warning = FALSE, table.cap = "Table 1. F40% and catch corresponding to F40% for each model run. Only Western-Central GOA is shown for two area models as there is no fishery in the Eastern GOA. Projections assume future catch equal to the average of the most recent five years."}

MS_Table_OneArea_NoFages<-get_refpts(ProjDir=here("projections","OneArea_NoFages","GrowthMorph1"),LastYr = 2021)

MS_Table_OneArea_Fages<-get_refpts(ProjDir=here("projections","OneArea_Fages","GrowthMorph1"),LastYr = 2021)

MS_Table_TwoArea_Fages<-get_refpts(ProjDir=here("projections","TwoArea_Fages","GrowthMorph2"),LastYr = 2021)

MS_Table_TwoArea_Fages_GP1<-get_refpts(ProjDir=here("projections","TwoArea_Fages","GrowthMorph1"),LastYr = 2021)

MS_Table_TwoArea_NoFages<-get_refpts(ProjDir=here("projections","TwoArea_NoFages","GrowthMorph2"),LastYr = 2021)

MS_Table_TwoArea_NoFages_GP1<-get_refpts(ProjDir=here("projections","TwoArea_NoFages","GrowthMorph1"),LastYr = 2021)

```
```{r plot comparison of survey indices, echo = FALSE, message = FALSE, warning = FALSE}
#Legends on bottom left
SSplotComparisons(OneAreaSummaryList,print = TRUE,plotdir = here("doc","sscompare","oneareamodels"),legendlabels = c(M1,M2),legendloc = "bottomleft",sprtarg = 0.6,minbthresh = 0,btarg = 0,indexQlabel = F,indexUncertainty = T)

SSplotComparisons(TwoAreaSummaryList,print = TRUE,plotdir = here("doc","sscompare","twoareamodels"),legendlabels = c(M3,M4),legendloc = "bottomleft",sprtarg = 0.6,minbthresh = 0,btarg = 0,indexQlabel = F,indexUncertainty = T)

SSplotComparisons(SummaryList,print = TRUE,plotdir = here("doc","sscompare","allmodels"),legendlabels = c(M1,M2,M3,M4),legendloc = "bottomleft",sprtarg = 0.6,minbthresh = 0,btarg = 0,indexQlabel = F,indexUncertainty = T)




```

