---
title: "Figures"
output: 
  word_document:
    reference_docx: carey_template.docx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(AreaGrowthRex)
library(ggplot2)
library(here)
library(ggpubr)
library(devtools)
library(r4ss)
library(patchwork)
```

```{r plotting themes, include=FALSE}

# Presentation theme
.THEME <- theme(panel.grid.major.x = element_blank(), panel.grid.minor.y = element_blank(), panel.grid.major.y = element_blank() )
.THEME <- .THEME + theme(text=element_text(size=18)) + theme(axis.title.x=element_text(size=24) ,axis.title.y=element_text(size=24, angle = 90,vjust = +2)) +
theme(legend.position = "bottom")
theme_set(.THEME)
#.THEME <- .THEME + theme( panel.background = element_rect(fill="white"), #panel.border = element_rect(colour="black", fill=NA, size=1))

# Manuscript theme
.THEME <- theme(panel.grid.major.x = element_blank(), panel.grid.minor.y = element_blank(), panel.grid.major.y = element_blank() )
.THEME <- .THEME + theme(text=element_text(size=12)) + theme(axis.title.x=element_text(size=12) ,axis.title.y=element_text(size=12, angle = 90,vjust = +2)) +
theme(legend.position = "bottom")
theme_set(.THEME)
```

```{r readfiles, include = FALSE, message = FALSE, warning = FALSE}
M1 <- file.path("ss", "OneArea_NoFages")
M2 <- file.path("ss", "OneArea_Fages")
M3 <- file.path("ss", "TwoArea_NoFages")
M4 <- file.path("ss", "TwoArea_Fages")

Mlab.1 <- "OneArea_NoFages"
Mlab.2 <- "OneArea_Fages"
Mlab.3 <- "TwoArea_NoFages"
Mlab.4 <- "TwoArea_Fages"

Mlabels <- c(Mlab.1, Mlab.2, Mlab.3, Mlab.4)
MasterList <- r4ss::SSgetoutput(dirvec = c(M1, M2, M3, M4), getcomp = TRUE, getcovar = TRUE)

OneAreaList <- r4ss::SSgetoutput(dirvec = c(M1, M2), getcomp = TRUE, getcovar = TRUE)

TwoAreaList <- r4ss::SSgetoutput(dirvec = c(M3, M4), getcomp = TRUE, getcovar = TRUE)



OneAreaSummaryList <- r4ss::SSsummarize(OneAreaList)
TwoAreaSummaryList<- r4ss::SSsummarize(OneAreaList)
SummaryList<-r4ss::SSsummarize(MasterList)
```

```{r plotruns, include = FALSE, message = FALSE, warning = FALSE}
# MyOutput = r4ss::SS_output(dir = M1,covar = TRUE,forecast=TRUE)
# r4ss::SS_plots(replist = MyOutput,uncertainty=TRUE) #, #plot = 2:24) 
# 
# MyOutput = r4ss::SS_output(dir = M2,covar = TRUE,forecast=TRUE)
# r4ss::SS_plots(replist = MyOutput,uncertainty=TRUE) #, plot = 2:24) 
# 
# MyOutput = r4ss::SS_output(dir = M3,covar = TRUE,forecast=TRUE)
# r4ss::SS_plots(replist = MyOutput,uncertainty=TRUE) #, plot = 2:24) 
# 
# MyOutput = r4ss::SS_output(dir = M4,covar = TRUE,forecast=TRUE)
# r4ss::SS_plots(replist = MyOutput,uncertainty=TRUE) #, plot = 2:24) 
```

```{r plot lengths, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Figure 1. Fits (lines) to female and male length composition data aggregated by year (shaded regions) for the one area model without fishery ages included in model inputs (green) and with fishery ages included in model inputs (blue)."}
p<-plot_comps_onearea(ssruns = MasterList, narea = 1, mnames = Mlabels,comptype = "length", saveplots = TRUE)

p$combo
#p$noages
#p$ages
```


```{r plot ages, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Figure 2. Fits (lines) to female and male fishery age composition with data aggregated by year (shaded regions) for the one area model with fishery ages included in model inputs."}
q<-plot_comps_onearea(ssruns = MasterList, narea = 1, mnames = Mlabels,comptype = "age")
q$combo
```


```{r plot growth, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Figure 3. Raw bottom trawl survey data length-at-age by area and sex, overlayed with mean length-at-age for each model (columns) and 90% asymptotic uncertainty intervals around the means (shaded areas). The Eastern GOA is shown in green and the Western-Central GOA is shown in blue."}
g<-plot_growth(ssruns=MasterList,sslabels=Mlabels,savePlot = FALSE)
g
ggsave(filename = file.path("doc",paste0("Plot_Growth_AllModels.png")),device = "png",width = 10,height = 5)

```
```{r plot length comps two area models, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Figure 4. Fits (lines) to female and male fishery length composition with data aggregated by year (shaded regions) for the two-area area model."}
q<-plot_comps_onearea(ssruns = MasterList, narea = 2, mnames = Mlabels,comptype = "length")
q$combo
```

```{r plot ages two area models, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Figure 5. Fits (lines) to female and male fishery age composition with data aggregated by year (shaded regions) for the two-area area model with fishery ages included in model inputs."}
q<-plot_comps_onearea(ssruns = MasterList, narea = 2, mnames = Mlabels,comptype = "age")
q$combo
```
```{r plot estimated pop dynamics, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Figure 6. Observed catches and estimated spawning biomass, recruitment, and fishing intensity (1-spawning potential ratio) for each of the four alternative models"}
#need to make y-axis on ssb go to zero
ssbplot<-plot_ssbs(ssruns=MasterList,mlabel=Mlabels,showxlabel =   FALSE,showlegend = "none")
recplot<-plot_recs(ssruns = MasterList,mlabel = Mlabels,showxlabel = TRUE,showlegend = "yes")

bigfig<-(ssbplot/recplot)
# my_plot_list<-list(ssbplot,recplot)
# fig<-ggarrange(plotlist = c(ssbplot,recplot),label = c("a","b"),ncol = 1, nrow = 2)
#aspirational:
#c<-plot_catches(ssruns = MasterList,mlabel = Mlabels,showlegend = TRUE)
#f<-plot_one_minus_spr(ssruns = MasterList,mlabel = Mlabels,showlegend = TRUE)

#some sort of aes mapping issue here
#ggarrange(r,s,labels = c("a","b"), nrow = 2, ncol = 1, common.legend = TRUE, legend="bottom")

#rs
#ggsave(filename = file.path(plot = rs,"doc",paste0("Compare_TimeSeries.png")),device = "png",width = 8.5,height = 11)
```
```{r plot selectivity overlaid on maturity, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Figure 7. Fishery and survey selectivity-at-age across models for males and females. Plots for females are overlaid on maturity-at-age"}
p<-plot_selex_maturity(ssruns=MasterList,mlabels=Mlabels) 
ggsave(filename = file.path("doc",paste0("Plot_Selex_Maturity_AllModels.png")),device = "png",width = 10,height = 7)


```

```{r get the projection data file for each model run but right now organizing the projections manually within the projections folder, echo = FALSE, message = FALSE, warning = FALSE}


get_projections(mydir = here(M1) ,MyOutput = MasterList[[1]],NagesProject = 20,FirstYr = 1982,LastYr = 2021,RecruitmentAge=3,species="Rex")

get_projections(mydir = here(M2) ,MyOutput = MasterList[[2]],NagesProject = 20,FirstYr = 1982,LastYr = 2021,RecruitmentAge=3,species="Rex")

get_projections(mydir = here(M3) ,MyOutput = MasterList[[3]],NagesProject = 20,FirstYr = 1982,LastYr = 2021,RecruitmentAge=3,species="Rex")

get_projections(mydir = here(M4) ,MyOutput = MasterList[[4]],NagesProject = 20,FirstYr = 1982,LastYr = 2021,RecruitmentAge=3,species="Rex")

```

```{r grab ref pts from projection results, echo = FALSE, message = FALSE, warning = FALSE, table.cap = "Table 1. F40% and catch corresponding to F40% for each model run. Only Western-Central GOA is shown for two area models as there is no fishery in the Eastern GOA. Projections assume future catch equal to the average of the most recent five years."}

MS_Table_OneArea_NoFages<-get_refpts(ProjDir=here("projections","OneArea_NoFages","GrowthMorph1"),LastYr = 2021)

MS_Table_OneArea_Fages<-get_refpts(ProjDir=here("projections","OneArea_Fages","GrowthMorph1"),LastYr = 2021)

MS_Table_TwoArea_Fages<-get_refpts(ProjDir=here("projections","TwoArea_Fages","GrowthMorph2"),LastYr = 2021)

MS_Table_TwoArea_Fages_GP1<-get_refpts(ProjDir=here("projections","TwoArea_Fages","GrowthMorph1"),LastYr = 2021)

MS_Table_TwoArea_NoFages<-get_refpts(ProjDir=here("projections","TwoArea_NoFages","GrowthMorph2"),LastYr = 2021)

MS_Table_TwoArea_NoFages_GP1<-get_refpts(ProjDir=here("projections","TwoArea_NoFages","GrowthMorph1"),LastYr = 2021)

```
```{r plot comparison of survey indices, echo = FALSE, message = FALSE, warning = FALSE}
#Legends on bottom left
SSplotComparisons(OneAreaSummaryList,print = TRUE,plotdir = here("doc","sscompare","oneareamodels"),legendlabels = c(M1,M2),legendloc = "bottomleft",sprtarg = 0.6,minbthresh = 0,btarg = 0,indexQlabel = F,indexUncertainty = T)

SSplotComparisons(TwoAreaSummaryList,print = TRUE,plotdir = here("doc","sscompare","twoareamodels"),legendlabels = c(M3,M4),legendloc = "bottomleft",sprtarg = 0.6,minbthresh = 0,btarg = 0,indexQlabel = F,indexUncertainty = T)

SSplotComparisons(SummaryList,print = TRUE,plotdir = here("doc","sscompare","allmodels"),legendlabels = c(M1,M2,M3,M4),legendloc = "bottomleft",sprtarg = 0.6,minbthresh = 0,btarg = 0,indexQlabel = F,indexUncertainty = T)




```

